#
# Dockerfile for DockerHub automatic build of postfwd - http://postfwd.org/docker
#
# If you want to rebuild it, go to the top directory (usually 'cd ..') and type in:
#
#	docker build -f docker/Dockerfile-autobuild -t postfwd:mybuild .
#
# To run a container from it, use:
#
#	docker run -it postfwd:mybuild
#
# or with more options (postfwd2 on port 10050, postfwd.cf in /path/to/ruleset):
#
#	docker run -it -e PROG=postfwd2 -e PORT=10050 -v /path/to/ruleset:/etc/postfwd:ro postfwd:mybuild
#
FROM debian:stretch-slim

LABEL maintainer="Postfwd Docker - http://postfwd.org/docker"

##
## RUNTIME ARGS
##
# use 'postfwd1' or 'postfwd2' to switch between versions
# go to http://postfwd.org/versions.html for more info
ENV PROG=postfwd1
# port for postfwd
ENV PORT=10040
# request cache in seconds. use '0' to disable
ENV CACHE=60
# additional arguments, see postfwd -h or man page for more
ENV EXTRA="--noidlestats --summary=600"
# get config file from ARG
ENV CONF=postfwd.cf

##
## CONTAINER ARGS
##
# configuration directory
ENV ETC=/etc/postfwd
# target for postfwd distribution
ENV TARGET=/usr/local
# sub-directory for postfwd distribution files
ENV TARGETSUB=postfwd
# data directory
ENV HOME=/var/lib/postfwd
# user and group for execution
ENV USER=postfw
ENV GROUP=postfw

# install stuff
RUN apt-get update && apt-get install --no-install-recommends -y \
    libnet-dns-perl libnet-server-perl libnetaddr-ip-perl \
    libtime-hires-perl libstorable-perl
RUN rm -fR /var/lib/apt/lists/*

# create stuff
RUN addgroup --quiet --system ${GROUP}
RUN adduser --quiet --system --no-create-home --disabled-login --disabled-password \
    --ingroup ${GROUP} --home ${HOME} --shell /bin/false ${USER}
RUN mkdir -p ${ETC} && chown root:${GROUP} ${ETC} && chmod 0750 ${ETC}
RUN mkdir -p ${HOME} && chown ${USER}:${GROUP} ${HOME} && chmod 0700 ${HOME}
RUN mkdir -p ${TARGET} && chown root:root ${TARGET} && chmod 0755 ${TARGET}
RUN mkdir -p ${TARGETSUB} && chown root:root ${TARGETSUB} && chmod 0755 ${TARGETSUB}

# copy stuff
COPY ./sbin/    ${TARGET}/sbin/
COPY ./bin/     ${TARGET}/bin/
COPY ./man/     ${TARGET}/man/
COPY ./doc/     ${TARGET}/${TARGETSUB}/doc/
COPY ./plugins/ ${TARGET}/${TARGETSUB}/plugins/
COPY ./tools/   ${TARGET}/${TARGETSUB}/tools/
COPY ./etc/	${ETC}/
RUN chown -R root:root ${TARGET}

# open port
EXPOSE ${PORT}

# start postfwd - don't worry about versions: postfwd1 will silently ignore postfwd2-specific arguments
ENTRYPOINT exec ${TARGET}/sbin/${PROG} --file ${ETC}/${CONF} --user ${USER} --group ${GROUP} \
	--server_socket tcp:0.0.0.0:${PORT} --cache_socket=unix::${HOME}/postfwd.cache \
	--pidfile=${HOME}/postfwd.pid --save_rates=${HOME}/postfwd.rates \
	--cache=${CACHE} ${EXTRA} \
	--stdout --nodaemon

